name: Build Linux x64

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Build mode"
        required: true
        default: standalone
        type: choice
        options: [standalone, onefile]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Prepare build environment
        run: bash build/containers/setup-linux.sh

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: nuitka-cache-${{ inputs.mode }}
          key: "nuitka-linux_x64-${{ inputs.mode }}-${{ hashFiles('requirements.txt', 'src/**/*.py') }}"
          restore-keys: |
            "nuitka-linux_x64-${{ inputs.mode }}-"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "nuitka>=2.3.7" ordered-set zstandard -r requirements.txt

      - name: Build
        env:
          NUITKA_CACHE_DIR: "nuitka-cache-${{ inputs.mode }}"
        run: bash build/linux-x64.sh ${{ inputs.mode }}

      - uses: actions/upload-artifact@v4
        with:
          name: pyasciifilm-linux-x64${{ inputs.mode == 'onefile' && '-onefile' || '' }}
          path: |
            dist/standalone/*.tar.gz
            dist/onefile/PyAsciiFilm-*-linux_x64
          if-no-files-found: error
          compression-level: 9
