name: Build macOS ARM64

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Build mode"
        required: true
        default: standalone
        type: choice
        options: [standalone, onefile]

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"
          cache: pip
          cache-dependency-path: requirements.txt
      - run: pip install "nuitka>=2.3.7" ordered-set zstandard -r requirements.txt

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/nuitka-cache-${{ inputs.mode }}
          key: "nuitka-macos_arm64-${{ inputs.mode }}-${{ hashFiles('requirements.txt', 'src/**/*.py') }}"
          restore-keys: |
            "nuitka-macos_arm64-${{ inputs.mode }}-"

      - name: Build
        env:
          NUITKA_CACHE_DIR: "${{ runner.temp }}/nuitka-cache-${{ inputs.mode }}"
        run: bash build/macos-arm64.sh ${{ inputs.mode }}

      - uses: actions/upload-artifact@v4
        with:
          name: pyasciifilm-macos-arm64${{ inputs.mode == 'onefile' && '-onefile' || '' }}
          path: |
            dist/standalone/PyAsciiFilm-*.zip
            dist/onefile/PyAsciiFilm-*-macos_arm64
          if-no-files-found: error
          compression-level: 9
